### ISSUE TITLE
Adding Romberg Method - Question about tests

### ISSUE THREAD

**Issue by bernatguillen** [dextorious/NumericalIntegration.jl#13]
I've added Romberg's method for higher precision integration (with the inconvenient that you need 2^n + 1 evenly sampled points). It's my first project in Julia and I am having problems adding support for Static Arrays. What's the recommended procedure? Should i send a PR with the test failing? Should I add an exception to the test so it doesn't test Romberg? Or should I not send a PR until the SVector test works as well?

**Comment by dextorious** [comment]
Thanks for your interest! You can put up a PR whenever you'd like me to look at it. I won't merge it until the tests all work, but I don't mind taking a look when I get a chance - even if I don't see a quick fix, you can still keep working on the code in the meantime, the PR will update itself.

**Comment by dextorious** [comment]
Resolved in https://github.com/dextorious/NumericalIntegration.jl/pull/14.
