### ISSUE TITLE
Slower than Trapz.jl

### ISSUE THREAD

**Issue by francescoalemanno** [dextorious/NumericalIntegration.jl#18]
## Comparison against Trapz.jl

I believe NumericalIntegration.jl package is much better structured and complete, though the integration routine could use some speed improvement, indeed the simple code in Trapz.jl is 13-16 times faster than the TrapezoidalFast() mode in this package.

If i used your package incorrently then i apologize in advance.
EDIT: old benchmark [Old link](https://github.com/francescoalemanno/Trapz.jl/blob/289ff5f72a8aa395c9771eb6df14f8b34162bfe6/benchmarks/Comparison_Trapz_NumericalIntegration.ipynb)

Updated benchmark after bugfix in Trapz: [Here](https://github.com/francescoalemanno/Trapz.jl/blob/master/benchmarks/Comparison_Trapz_NumericalIntegration.md)

**Comment by dextorious** [comment]
Very interesting, thank you for the report! At a very cursory glance I don't see anything obviously wrong with your benchmark, but I'll try to figure out the cause over the weekend. If Trapz.jl is really that much faster on the same algorithm, that's a bug in NumericalIntegration.jl and will get fixed.

**Comment by dextorious** [comment]
On my machine NumericalIntegration.jl is about 11% faster when you use the `TrapezoidalEvenFast()` method, which assumes evenly spaced inputs. Does Trapz make that assumption as well?

**Comment by francescoalemanno** [comment]
No. anyway it's easy to look at Trapz.jl [code](https://github.com/francescoalemanno/Trapz.jl/blob/master/src/Trapz.jl) as it is ~35 lines long without doc-lines. 
if i assume a uniform spacing as in TrapezoidalEvenFast()


```julia
using BenchmarkTools
trapz_even(vx,trapz_even(vy,M)) , integrate((vx,vy),M,TrapezoidalFast())
```




    (2.333401012651792, 2.333401012651791)




```julia
@benchmark trapz_even($vx,trapz_even($vy,$M))
```




    BenchmarkTools.Trial: 
      memory estimate:  15.81 KiB
      allocs estimate:  301
      --------------
      minimum time:     9.608 μs (0.00% GC)
      median time:      10.411 μs (0.00% GC)
      mean time:        21.761 μs (39.72% GC)
      maximum time:     58.930 ms (99.91% GC)
      --------------
      samples:          10000
      evals/sample:     1




```julia
T=(vx,vy)
mode=TrapezoidalEvenFast()
@benchmark integrate($T,$M,$mode) 
```




    BenchmarkTools.Trial: 
      memory estimate:  11.39 KiB
      allocs estimate:  204
      --------------
      minimum time:     11.880 μs (0.00% GC)
      median time:      12.505 μs (0.00% GC)
      mean time:        25.303 μs (37.93% GC)
      maximum time:     72.456 ms (99.92% GC)
      --------------
      samples:          10000
      evals/sample:     1

### Edit
made available the method in Trapz.jl, quick patch

**Comment by dextorious** [comment]
With that addition, I'm getting:
```
julia> @benchmark trapz_even($vx,trapz($vy,$M))
BenchmarkTools.Trial: 
  memory estimate:  15.81 KiB
  allocs estimate:  301
  --------------
  minimum time:     6.354 μs (0.00% GC)
  median time:      7.027 μs (0.00% GC)
  mean time:        8.044 μs (10.00% GC)
  maximum time:     1.971 ms (99.28% GC)
  --------------
  samples:          120803
  evals/sample:     5

julia> @benchmark integrate(($vx,$vy),$M,$TrapezoidalEvenFast())
BenchmarkTools.Trial: 
  memory estimate:  11.39 KiB
  allocs estimate:  204
  --------------
  minimum time:     6.055 μs (0.00% GC)
  median time:      6.440 μs (0.00% GC)
  mean time:        7.195 μs (9.31% GC)
  maximum time:     7.411 ms (99.81% GC)
  --------------
  samples:          136110
  evals/sample:     5
```
so the even methods seem fine. I'll take a look at what's making the general case slow.

**Comment by francescoalemanno** [comment]
```
With that addition, I'm getting:

julia> @benchmark trapz_even($vx,trapz($vy,$M))
```
this is benchmarking both functions, anyway i agree! :smiley:

**Comment by dextorious** [comment]
Heh, yeah, that's my bad. Properly using `trapz_even` makes your version a bit less than 5% faster still. Here's the interesting part, though - if I compare `trapz_even` and `integrate` on 1D input, the latter is faster  by like 80x, all the slowdown comes in from the multidimensional stuff.

**Comment by dextorious** [comment]
Okay, the basic issue here as I understand it (which Trapz.jl also shares, but to a lesser extent) is that the compiler fails to fully inline everything and elide the views, instead we get a bunch of heap allocations and code bloat. Eventually the compiler should be able to deal with it, but in the meantime all of the possible solutions are fairly ugly. I could just get rid of the views entirely, but that would mean rewriting all the integration kernels by hand for each method. Not quite sure it's particularly worth it, but I might just do it once for the most common case (the even Trapezoidal method).

**Comment by francescoalemanno** [comment]
This makes a lot of sense! following your advice i took a quick look at the code_native by trapz method, and code_native for a purely 1d version, there is a lot! of code bloat due to broadcasting and views in my case, 


Thank you, for your time!

**Comment by m-wells** [comment]
I'm hoping that [Julia v1.5 solved this issue](https://github.com/JuliaLang/julia/issues/14955).
