### ISSUE TITLE
Could you register the latest version?

### ISSUE THREAD

**Issue by SebastianM-C** [dextorious/NumericalIntegration.jl#29]
Hi!

Thanks for making this package. The GitHub page shows a [v0.3.0 tag](https://github.com/dextorious/NumericalIntegration.jl/releases/tag/v0.3.0), but there is no [registered version of this package with that version](https://github.com/JuliaRegistries/General/blob/master/N/NumericalIntegration/Versions.toml) in the General registry.

**Comment by SebastianM-C** [comment]
@dextorious I think that the `JuliaRegistrator` comment must be either in an issue or in a comment to a commit (ref: https://github.com/JuliaRegistries/Registrator.jl#details-for-triggering-juliaregistrator-for-step-2-above).

**Comment by dextorious** [comment]
Sorry for the late reply. I'm not sure what the JuliaRegistrator issue was, but the JuliaHub web UI worked for me: https://github.com/JuliaRegistries/General/pull/26861

**Comment by SebastianM-C** [comment]
I think the issue was that the comment was on the release and not on the commit.

It looks like the auto-merge failed, one of the reasons being the lack of compat bounds for `Interpolations`. If you'd like I can make a PR adding CompatHelper, so that this kind of issues can be avoided in the future.

**Comment by dextorious** [comment]
That would be great, if it's not too much trouble. This is my first time dealing with the current registry system, so I'm a bit confused. I don't think I can avoid the version jump without editing the git history, but at least the compat bounds issue can hopefully be dealt with.

**Comment by SebastianM-C** [comment]
I asked on slack about the tag version issue and the options are
- delete the tag(s) and register v0.3.0
- comment on the General registry PR and say that you are happy to jump to 0.3.2 directly

I think that you could try to register again now with the `JuliaRegistrator` command or the web UI since the compat issue is solved now.

**Comment by SebastianM-C** [comment]
@dextorious I think the simplest course of action would be to just comment in the [General registry PR](https://github.com/JuliaRegistries/General/pull/26861) and mention that you are fine with skipping over `v0.3.0` so that the PR can be merged (the default course of action is to do nothing and close the PR if inactive for too long).

**Comment by SebastianM-C** [comment]
The v0.3.2 was successfully registered, thanks!
There seems to be a problem with the tags, but I'll continue that in a separate issue: #36
