### ISSUE TITLE
Update TagBot

### ISSUE THREAD

**Issue by SebastianM-C** [dextorious/NumericalIntegration.jl#36]
Due to the fact that GitHub disables actions with cron jobs on repositories that don't have activity for 60days, TagBot and CompatHelper might get disabled (see https://github.com/dextorious/NumericalIntegration.jl/actions?query=workflow%3ATagBot). For TagBot there is a solution which gets triggered by comments (see https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249). I've made a PR for this in #35 

Because of this issue the latest tag was not registered (and will have to be manually created I think).

**Comment by dextorious** [comment]
Thank you! I've merged the PR, hopefully that's enough to keep TagBot active.
