### ISSUE TITLE
Should I contribute here?

### ISSUE THREAD

**Issue by jw3126** [dextorious/NumericalIntegration.jl#9]
I need to integrate presampled 1d functions and this package seems to do exactly that job :smile: 
I now consider contributing. However there is a zoo of integration packages and before I do any work, I wanted to make sure that this is not abandoned in favor of some other package?

**Comment by dextorious** [comment]
It's not abandoned in the sense that it's being ignored, but I did consider it largely feature complete for the simple usecase it was originally intended for. I don't follow this very closely, but I don't know of any other non-abandoned Julia package with support for integration of presampled data, so you're probably in the right place in that regard.

If you'd like to contribute additional functionality, I'm happy to review pull requests and merge them if they don't break anything, have tests and conform to the general spirit of the package - a unified, simple user-facing API and a general emphasis for clarity and performance over handling every conceivable special case out there. If you have some ideas and you're not sure whether they'd fit in here, we can discuss them before you invest too much work into it. Thanks for your interest!

**Comment by jw3126** [comment]
Okay thanks! Here is some stuff I would find useful:

* Often I have presampled data `xs, ys` and I would like to integrate not the complete data, but only over an interval `a,b` where `min(xs) < a < b < max(xs)`. I would like to add a keyword argument
`integrate(xs, ys, method; window=nothing)` such that `window=(a,b)` restricts the integral to `(a,b,)`. 
* Currently `integral` will mostly give back a `Float64` if you feed vectors with eltype `Float32`. I would like it to give back the eltype of the original arrays if possible.
* Currently only `AbstractVector{<:Number}` is accepted as an argument. I sometimes have vector valued signals, so I would like to change to `ys::AbstractVector`. Or even drop type restriction altogether.

**Comment by dextorious** [comment]
I'm totally in favor of the latter two points. As for the keyword argument idea, that's technically a performance regression until we get fast kwargs in 0.7, albeit a very small one. If you don't see a meaningful difference for small inputs (say, of length 10 or so), great, otherwise we might need to abstract that to a wrapper that users can use or avoid as they see fit.
